apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - appName: 1
        namespace: guestbook-1
      - appName: 2
        namespace: guestbook-2
  template:
    metadata:
      name: '{{appName}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/Marvin9/argocd-example-apps
        targetRevision: HEAD
        path: guestbook
      destination:
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true

