apiVersion: v1
kind: Namespace
metadata:
  name: argocd-2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd-2
spec:
  project: default
  source:
    repoURL: https://github.com/Marvin9/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: http://cluster-macbook:8001
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
