apiVersion: v1
kind: Namespace
metadata:
  name: argocd-2
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-2
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceNamespaces:
  - '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd-2
spec:
  project: default-2
  source:
    repoURL: https://github.com/Marvin9/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: http://cluster-macbook:8001
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
