apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Marvin9/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: http://cluster-macbook:8001
    namespace: argocd2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
