helm:
  parameters:
  - name: image.repository
    value: registry-1.docker.io/mayursiinh/test-image-updater
    forcestring: false
  - name: image.tag
    value: 2.0.0
    forcestring: true
  - name: image.name
    value: registry-1.docker.io/mayursiinh/test-image-updater
    forcestring: true
